### ISSUE TITLE
some 

### ISSUE THREAD

**Issue by npu2018302386** [canerozer/explainable-iqa#1]
Hi, why the code for training the resnet34 classification model is not given, but a weight file is directly given. According to the training method in the paper, I did not get such a highly efficient model. Can you give me the code for model training? thanks.

**Comment by canerozer** [comment]
Hello, 
You can access the code for training of the ResNet-34 model, however, I may not fully verify if that should work without some editing, because we may had done some modifications on the inference code to make it run on the codalab infrastructure. We did not mention the training procedure of the model since that was a little bit out of scope of our paper.

https://worksheets.codalab.org/bundles/0x0999eb4257fb4e9db652c04f5c233afd

**Comment by npu2018302386** [comment]
thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Caner ***@***.***&gt;; 
发送时间: 2021年11月21日(星期天) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [canerozer/explainable-iqa] some  (Issue #1)





 
Hello,
 You can access the code for training of the ResNet-34 model, however, I may not fully verify if that should work without some editing, because we may had done some modifications on the inference code to make it run on the codalab infrastructure. We did not mention the training procedure of the model since that was a little bit out of scope of our paper.
 
https://worksheets.codalab.org/bundles/0x0999eb4257fb4e9db652c04f5c233afd
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
